// constants/errorCodes.js
export const ERROR_CODES = {
  // General errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",

  // Database errors
  DATABASE_ERROR: "DATABASE_ERROR",

  // Procedure-specific errors
  PROC_ERROR: "PROC_ERROR",
  ALREADY_RUNNING: "ALREADY_RUNNING",
  TIMEOUT: "TIMEOUT",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
};
