// constants/errorCodes.js
export const ERROR_CODES = {
  // General errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // Database errors
  DATABASE_ERROR: "DATABASE_ERROR",
  CONNECTION_ERROR: "CONNECTION_ERROR",
  QUERY_ERROR: "QUERY_ERROR",

  // Procedure-specific errors
  PROC_ERROR: "PROC_ERROR",
  ALREADY_RUNNING: "ALREADY_RUNNING",
  TIMEOUT: "TIMEOUT",
  LOCK_ERROR: "LOCK_ERROR",

  // Business logic errors
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  OPERATION_FAILED: "OPERATION_FAILED",
};
